spring:
  datasource:
    url : jdbc:mysql://test-db.cpgoq4gweryz.us-east-2.rds.amazonaws.com:3306/test
    username : root
    password : wnsgud6208
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate